id: I7BEA4C27
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T23:43:30+00:00'
last_modified: '2022-06-07T12:27:11.487461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22545
  title: སྔོན་འགྲོ་ཆོས་སྤྱོད་ཐར་ལམ་དཀར་པོ་དང་གསོལ་འདེབས་སྨོན་ལམ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9700':
      image_group_id: I1KG22555
      title: ''
      total_pages: 514
      order: 1
      base_file: 9700.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
