id: P000613
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22545
  title: སྔོན་འགྲོ་ཆོས་སྤྱོད་ཐར་ལམ་དཀར་པོ་དང་གསོལ་འདེབས་སྨོན་ལམ་སོགས།
  author: ''
  volumes:
    e08826ddc4cc420cad4406db4205ff14:
      image_group_id: I1KG22555
      title: ''
      volume_number: 1
      total_pages: 514
