id: P000613
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:51:35.552947
source_metadata:
  id: bdr:W1KG22545
  title: སྔོན་འགྲོ་ཆོས་སྤྱོད་ཐར་ལམ་དཀར་པོ་དང་གསོལ་འདེབས་སྨོན་ལམ་སོགས།
  author: ''
  volumes:
    e08826ddc4cc420cad4406db4205ff14:
      image_group_id: I1KG22555
      title: ''
      volume_number: 1
      total_pages: 514
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
